# Generated by Django 4.2.16 on 2024-11-22 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0002_status_plea_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plea',
            name='status',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
        migrations.AddField(
            model_name='plea',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
