# Generated by Django 4.2.16 on 2024-11-23 02:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('studio', '0003_remove_plea_status_delete_status_plea_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='plea',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='plea',
            name='category',
        ),
        migrations.AlterField(
            model_name='plea',
            name='status',
            field=models.CharField(blank=True, choices=[('n', 'Новая'), ('c', 'Выполнено')], default='n', help_text='Статус заявки', max_length=1),
        ),
        migrations.AddField(
            model_name='plea',
            name='category',
            field=models.ForeignKey(help_text='Выберите категорию заявки', null=True, on_delete=django.db.models.deletion.SET_NULL, to='studio.category'),
        ),
    ]
