# Generated by Django 4.2.16 on 2024-11-23 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0004_plea_author_remove_plea_category_alter_plea_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plea',
            name='plan',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
