# Generated by Django 4.2.16 on 2024-11-23 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0005_alter_plea_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plea',
            name='plan',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
