# Generated by Django 4.2.16 on 2024-11-25 02:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0006_alter_plea_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='plea',
            name='creationDate',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='plea',
            name='status',
            field=models.CharField(blank=True, choices=[('n', 'Новая'), ('c', 'Выполнено'), ('i', 'принято в работу')], default='n', help_text='Статус заявки', max_length=1),
        ),
    ]
