# Generated by Django 4.2.16 on 2024-11-26 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0007_plea_creationdate_alter_plea_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plea',
            name='category',
            field=models.ForeignKey(help_text='Выберите категорию заявки', null=True, on_delete=django.db.models.deletion.CASCADE, to='studio.category'),
        ),
    ]
