# Generated by Django 4.2.16 on 2024-11-26 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0008_alter_plea_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='plea',
            name='comentary',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='plea',
            name='design',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
