# Generated by Django 4.2.16 on 2024-11-27 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0010_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='plea',
            name='adminUserName',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
